# $Revision$
* view-lock-mode
  view-mode のとき、しばらく触らないと印字キーをロックする拡張です.
  事故防止等で view-mode しておいたのを忘れて、
  少し経って編集しようとして素のキーにバインドされている isearch を動かしてしまったり、
  `q' でウィンドウを閉じてしまったりして、迷子になるのを防止するためのものです.
#  テキスト破壊事故防止で view-mode にしておいたのに view-mode で迷子という事故になる.

* 使い方
  [[https://github.com/s-fubuki/view-lock-mode][ここ]]から落とし load-path の通った位置に置き init.el 等に以下を追記します.

#+BEGIN_SRC emacs-lisp
(setq view-read-only t) ; これをしないと C-x C-q で `view-mode' にならない.
(autoload 'view-lock-mode "view-lock-mode" nil t)
(add-hook 'view-mode-hook #'(lambda () (view-lock-mode (if view-mode 1 -1))))
#+END_SRC

  /C-x C-q/ で `read-only-mode' にすると  `view-mode' になり、
  モードラインの `View' インジケータに色がつきます.

  `view-mode' のとき 5分間タイプがないと文字キーがロックされ
  `View' インジケータの色が変わります.
  文字キー(または改行)を打つと文字が打てずエコーエリアに
  その旨のメッセージが表示されるようになります.

  ロックされるのは印字キーと改行キーだけなので、
  コントロール系は勿論カーソル等ファンクション系のキーは素通りします.
  解除するには再び /C-x C-q/ とタイプします.

  ロック時 `M-q' とすると、最初に `C-x C-q' で起動した状態と同じ
  ロックスタンバイの状態になります.
  prefix を付け `C-u M-q' すると `view-lock-mode' だけが終了し
  プレーンな `view-mode' になります(が、あまり意味はないと思われる).

  ロック中のキー操作まとめると

  | C-x C-q | view-mode 共々完全に解除し編集可能になる                                |
  | M-q     | ロック解除され view-mode になり一定時間操作がないと再び自動ロックされる |
  | C-u M-q | ロック解除されプレーンな view-mode になる                               |


* カスタマイズ
** カスタム変数
*** view-lock-start-time
    キーに触れなくなってからロック開始するまでの秒数を整数で指定します.
    デフォルトは 300(5分)です.

*** view-lock-current-input-method
     non-nil だとロック時に IME を切ります(これも入れたままなのを忘れているので).
     デフォルトは `t' です.SKK でしか効力がないかもしれません.

*** view-lock-vc-faces
    VC に `read-only-mode' と連動させた部分があるので、
    モードラインの VC ステイタス表示が、フェイス `view-lock-vc' になるようにしてあります.

    この変数でリスト指定した VC のフェイスが対象になります[fn::VC face かどうかの整合性はチェックしていないのでスペルミスには注意してください.].
    不要な場合やVCフェイス側で設定する場合は `nil' にすると無効になります.
    デフォルトは \(vc-up-to-date-state vc-locked-state) です.
    # [fn:: RCS, CVS, Git で動作確認]

    RCS 等の Lock系の場合、自分がリポジトリをロックしていない状態だと
    (つまり編集できない状態なら) VC インジケータに色がつきます(-).
    Git 等のマージ系なら未編集なら着色され(-)で更新すると消灯します(:).
    共にワークファイルが未編集だと点灯しているということになります.

    # ワークファイルが未編集(リポジトリの最新と同一)なら VC インジケータに色がつきます.

*** view-lock-lighter
    view-lock-mode のインジケータ・ラベル文字列.
    先頭にスペースをひとつ入れてください.
    デフォルトは " View".

*** view-lock-shade
non-nil ならロックされたとき画面に日除けをおろします.
デフォルトは t で、ロックされると暗くなります.
(バッファが表のウィンドウでない場合稀になっていないバグがあります)

** フェイス
*** view-lock-highlight
    mode-line に表示される view-lock-mode インジケータのフェイス.
    デフォルトは `plum' または `gold4' で画面の明さによってどちらかになります.

*** view-lock-lock-highlight
    上記、ロック時のフェイス.
    デフォルトは `deep sky blue' または `green4'.

*** view-lock-vc
    カスタム変数 `view-lock-vc-faces' で指定されたフェイス属性をこのフェイスのものにします.
    `view-lock-highlight' からボールド属性を取り除いたものになっています.

*** view-lock-shade
同名変数が non-nil のとき画面を覆うフェイスです.
デフォルトは主に `dark slate blue' または `grey90' です.

* 前版からの変更点等
動作時画面を暗くするようにしました.

* 動作環境
> GNU Emacs 30.0.50 (build 1, x86_64-w64-mingw32) of 2023-04-16

